apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  # deployment labels
  labels:
    app: app1
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: nginx
        image: peddireddylokesh/app1:1.0.0
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector: # labels are used as the selectors
    app: app1
  ports:
  - protocol: TCP
    port: 80 # The port that the service will expose
    targetPort: 80
---